/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Practica1EDD;

import static Practica1EDD.ListaPersonajePlanta.flechaplanta2;
import static Practica1EDD.ListaPersonajePlanta.nodosplanta2;
import static Practica1EDD.ListaPersonajePlanta.flechazombie2;
import static Practica1EDD.ListaPersonajePlanta.nodoszombie2;
import static Practica1EDD.ListaPlanta.flechaplanta;
import static Practica1EDD.ListaPlanta.flechazombie;
import static Practica1EDD.ListaPlanta.nodosplanta;
import static Practica1EDD.ListaPlanta.nodoszombie;
import static Practica1EDD.Plantas.personajeP;
import static Practica1EDD.SecundariaPlanta.lp;
import static Practica1EDD.SecundariaZombi.zo;
import static Practica1EDD.Zombies.personajeZ;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Andrea
 */
public class Graficas extends javax.swing.JFrame {

    /**
     * Creates new form Graficas
     */
    public Graficas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("USUARIO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("PERSONAJE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Graficas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String grafico;
       grafico = "";
       
      
        lp.DibujarPlanta();
        zo.DibujarZombie();
        
        grafico = grafico + "digraph G{" + "\n" + "Usuario;" + "\n" + "Planta;"+ "\n" + "Zombie;" + "\n" + nodosplanta + "\n"
                + nodoszombie + "\n" + "Usuario->Planta->" + flechaplanta +  "\n" + "Usuario->Zombie->" + flechazombie + "}"; 
        System.out.println(grafico);
        

        if(grafico.matches("[[ ]*[\n]*[\t]]*"))
        {
            JOptionPane.showMessageDialog(null, "no hay texto para guardar!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            JFileChooser guardar = new JFileChooser();
            guardar.addChoosableFileFilter(new FileNameExtensionFilter("Todos los archivos *.txt",".TXT",".Txt"));
            int opcion = guardar.showSaveDialog(null);
            try{
                if (opcion == JFileChooser.APPROVE_OPTION)
                {
                   File f = guardar.getSelectedFile();
                   String path = f.getAbsolutePath();
                   PrintWriter pw = new PrintWriter(f);
                   pw.print(grafico);
                   pw.close();
                   
                   if(!(path.endsWith(".txt"))){
                       File temp = new File(path + ".Txt");
                       f.renameTo(temp);
                   }
                   JOptionPane.showMessageDialog(null, "Se Ha Guardado El Archivo Correctamente", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error Al Guardar El Archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
   
    try {

        String dotPath = "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe";

        String fileInputPath = "C:\\Users\\Andrea\\Desktop\\practica1_edd\\Jugador.txt";
        String fileOutputPath = "C:\\Users\\Andrea\\Desktop\\practica1_edd\\Jugador.jpg";

        String tParam = "-Tjpg";
        String tOParam = "-o";

        String[] cmd = new String[5];
        cmd[0] = dotPath;
        cmd[1] = tParam;
        cmd[2] = fileInputPath;
        cmd[3] = tOParam;
        cmd[4] = fileOutputPath;

        Runtime rt = Runtime.getRuntime();

        rt.exec(cmd);

    } catch (Exception ex) {
        ex.printStackTrace();
    } finally {
    }     

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String graficoP;
       graficoP = "";
       personajeP.DibujarPersonajePlanta();
       personajeZ.DibujarPersonajeZombie();
       
        
        graficoP = graficoP + "digraph G{" + "\n" + "Personaje;" + "\n" + "Planta;"+ "\n" + "Zombie;" + "\n" + nodosplanta2 + "\n"
                + nodoszombie2 + "\n" + "Personaje->Planta->" + flechaplanta2 +  "\n" + "Personaje->Zombie->" + flechazombie2 + "}"; 
        System.out.println(graficoP);
        

        if(graficoP.matches("[[ ]*[\n]*[\t]]*"))
        {
            JOptionPane.showMessageDialog(null, "no hay texto para guardar!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            JFileChooser guardar = new JFileChooser();
            guardar.addChoosableFileFilter(new FileNameExtensionFilter("Todos los archivos *.txt",".TXT",".Txt"));
            int opcion = guardar.showSaveDialog(null);
            try{
                if (opcion == JFileChooser.APPROVE_OPTION)
                {
                   File f = guardar.getSelectedFile();
                   String path = f.getAbsolutePath();
                   PrintWriter pw = new PrintWriter(f);
                   pw.print(graficoP);
                   pw.close();
                   
                   if(!(path.endsWith(".txt"))){
                       File temp = new File(path + ".Txt");
                       f.renameTo(temp);
                   }
                   JOptionPane.showMessageDialog(null, "Se Ha Guardado El Archivo Correctamente", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error Al Guardar El Archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
   
    try {

        String dotPath = "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe";

        String fileInputPath = "C:\\Users\\Andrea\\Desktop\\practica1_edd\\Personaje.txt";
        String fileOutputPath = "C:\\Users\\Andrea\\Desktop\\practica1_edd\\Personaje.jpg";

        String tParam = "-Tjpg";
        String tOParam = "-o";

        String[] cmd = new String[5];
        cmd[0] = dotPath;
        cmd[1] = tParam;
        cmd[2] = fileInputPath;
        cmd[3] = tOParam;
        cmd[4] = fileOutputPath;

        Runtime rt = Runtime.getRuntime();

        rt.exec(cmd);

    } catch (Exception ex) {
        ex.printStackTrace();
    } finally {
    }     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graficas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
